export enum MageSpell {
  Combustion = "Combustion",
  FireBlast = "Fire Blast",
  TimeWarp = "Time Warp",
  Fireball = "Fireball",
  Meteor = "Meteor",
  Pyroblast = "Pyroblast",
  PhoenixFlames = "Phoenix Flames",
  AlterTime = "Alter Time",
  RemoveCurse = "Remove Curse",
  Polymorph = "Polymorph",
  Scorch = "Scorch",
  FrostNova = "Frost Nova",
  Counterspell = "Counterspell",
  DragonsBreath = "Dragon's Breath",
  LivingBomb = "Living Bomb",
  Spellsteal = "Spellsteal",
  MirrorImage = "Mirror Image",
  RuneOfPower = "Rune of Power",
  BlazingBarrier = "Blazing Barrier",
  Invisibility = "Invisibility",
  IceBlock = "Ice Block",
  Blink = "Blink",
  Soulshape = "Soulshape",
  Flamestrike = "Flamestrike",
  RingOfFrost = "Ring of Frost",
  SlowFall = "Slow Fall",
  ArcaneExplosion = "Arcane Explosion",
  Frostbolt = "Frostbolt",
  ConjureRefreshment = "Conjure Refreshment",
  ArcaneIntellect = "Arcane Intellect",
}

export enum MageAura {
  HeatingUp = "Heating Up",
  HotStreak = "Hot Streak!",
  Combustion = "Combustion",
  BlazingBarrier = "Blazing Barrier",
  Tinder = "Tinder",
  Invisibility = "Invisibility",
  IceBlock = "Ice Block",
  PresenceOfMind = "Presence of Mind",
  ArcanePower = "Arcane Power",
  ManaShield = "Mana Shield",
  DampenMagic = "Dampen Magic",
  PrismaticBarrier = "Prismatic Barrier",
  IceBarrier = "Ice Barrier",
  ArcaneIntellect = "Arcane Intellect",
  SlowFall = "Slow Fall",
  Polymorph = "Polymorph",
  MeteorBurn = "Meteor Burn",
  IcyVeins = "Icy Veins",
  DB = "Dragon's Breath",
}
