import { PlayerAura } from "../../wowutils/wow_utils";
import { SpellstealPriority } from "../players/SpellstealPriority";
import { Warlock } from "../players/warlock";
import { DruidAura } from "./druid_utils";
import { HunterAura } from "./hunter_utils";
import { MageAura } from "./mage_utils";
import { PaladinAura } from "./paladin_utils";
import { PriestAura } from "./priest_utils";
import { ShamanAura } from "./shaman_utils";
import { WarlockAura } from "./warlock_utils";

export const SpellstealPriorityMap = new Map<PlayerAura, SpellstealPriority>();
SpellstealPriorityMap.set(MageAura.Combustion, SpellstealPriority.Required);
SpellstealPriorityMap.set(PaladinAura.LightsGrace, SpellstealPriority.Low);
SpellstealPriorityMap.set(PaladinAura.DivineFavor, SpellstealPriority.High);
SpellstealPriorityMap.set(PaladinAura.BlessingOfProtection, SpellstealPriority.High);
SpellstealPriorityMap.set(PaladinAura.BlessingOfFreedom, SpellstealPriority.Medium);
SpellstealPriorityMap.set(HunterAura.MastersCall, SpellstealPriority.Medium);
SpellstealPriorityMap.set(MageAura.IcyVeins, SpellstealPriority.High);
SpellstealPriorityMap.set(MageAura.BlazingBarrier, SpellstealPriority.High);
SpellstealPriorityMap.set(MageAura.ArcanePower, SpellstealPriority.High);
SpellstealPriorityMap.set(MageAura.PresenceOfMind, SpellstealPriority.Medium);
SpellstealPriorityMap.set(MageAura.PresenceOfMind, SpellstealPriority.Medium);
SpellstealPriorityMap.set(PriestAura.PowerWordFortitude, SpellstealPriority.Low);
SpellstealPriorityMap.set(PriestAura.PowerWordShield, SpellstealPriority.Medium);
SpellstealPriorityMap.set(DruidAura.Thorns, SpellstealPriority.High);
SpellstealPriorityMap.set(WarlockAura.NetherWard, SpellstealPriority.High);
SpellstealPriorityMap.set(WarlockAura.Backdraft, SpellstealPriority.Low);
SpellstealPriorityMap.set(ShamanAura.Heroism, SpellstealPriority.Medium);
SpellstealPriorityMap.set(ShamanAura.Bloodlust, SpellstealPriority.Medium);
SpellstealPriorityMap.set(WarlockAura.DarkSoulInstability, SpellstealPriority.High);
SpellstealPriorityMap.set(WarlockAura.DarkSoulMisery, SpellstealPriority.High);
